[uwsgi]
chdir = /srv/storefront/app
module = config.wsgi:application
home = /srv/storefront/venv
master = true
processes = 2
threads = 2
http-socket = /srv/storefront/run/uwsgi.sock
chmod-socket = 660
vacuum = true
harakiri = 60
max-requests = 2000
logto = /srv/storefront/logs/uwsgi.log
die-on-term = true
