"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qyk+f7-qlwk+@+sd8rt0x%z38h)t%q863a*$+u0c@@2oerinlp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "stores",
    "catalog",
    "orders",
    "console",
    "messaging",
    "integrations",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'console.context_processors.console_flags',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'  # site default; store schedules use Store.time_zone

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# MAILERS is configured from the environment further down, with the other overrides.


# --- storefront production overrides (reads /srv/storefront/.env) ---
import os
from urllib.parse import parse_qs, unquote, urlsplit

from dotenv import load_dotenv

load_dotenv(BASE_DIR.parent / ".env")

SECRET_KEY = os.environ["SECRET_KEY"]
DEBUG = os.environ.get("DEBUG") == "1"
ALLOWED_HOSTS = [h for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h]

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("DB_NAME", ""),
        "USER": os.environ.get("DB_USER", ""),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
        "PORT": "3306",
        "OPTIONS": {"charset": "utf8mb4"},
    }
}

if os.environ.get("DB_ENGINE") == "sqlite":
    DATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": BASE_DIR / "db.sqlite3"}}

STATIC_ROOT = BASE_DIR.parent / "static"
STATIC_URL = "/static/"

MIDDLEWARE.insert(0, "config.health.HealthCheckMiddleware")

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
CSRF_TRUSTED_ORIGINS = ["https://store.inkedgraphics.com", "https://*.inkedgraphics.com"]

# Hashed static names need a collectstatic manifest, which local dev and test runs don't
# build; plain storage serves {% static %} straight from the app static dirs.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
        if DEBUG
        else "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"
    },
}

# Media (uploads) live in S3 under media/; bucket is private, URLs are signed.
if os.environ.get("AWS_STORAGE_BUCKET_NAME"):
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": os.environ["AWS_STORAGE_BUCKET_NAME"],
            "region_name": "us-east-2",
            "endpoint_url": "https://s3.us-east-2.amazonaws.com",
            "location": "media",
            "default_acl": None,
            "querystring_auth": True,
            "querystring_expire": 3600,
            "file_overwrite": False,
        },
    }
else:
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"

# Email. Real SMTP once the server has credentials; until then nothing is silently dropped —
# dev prints to the console, production writes files under ../logs/emails/.
# Where cron jobs leave their heartbeat files (and flock their lock files, see deploy/cron.d).
RUN_DIR = os.environ.get("RUN_DIR") or str(BASE_DIR.parent / "run")

# Base URL for links in email sent outside a web request (the outbox runs from cron).
SITE_URL = os.environ.get("SITE_URL", "http://localhost:8000" if DEBUG else "https://store.inkedgraphics.com").rstrip("/")

DEFAULT_FROM_EMAIL = "Inked Graphics Stores <orders@inkedgraphics.com>"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

_email_url = os.environ.get("EMAIL_URL", "")
if _email_url:
    # e.g. smtp://user:pass@smtp.provider.com:587/ or smtps://... ("?tls=0" turns STARTTLS off)
    _parts = urlsplit(_email_url)
    _query = parse_qs(_parts.query)
    _ssl = _parts.scheme in ("smtps", "smtp+ssl")
    _smtp = {
        "host": _parts.hostname or "",
        "port": _parts.port or (465 if _ssl else 587),
        "username": unquote(_parts.username or ""),
        "password": unquote(_parts.password or ""),
        "use_ssl": _ssl,
        "use_tls": not _ssl and _query.get("tls", ["1"])[0] not in ("0", "false", "no"),
    }
elif os.environ.get("EMAIL_HOST"):
    _ssl = os.environ.get("EMAIL_USE_SSL") == "1"
    _smtp = {
        "host": os.environ["EMAIL_HOST"],
        "port": int(os.environ.get("EMAIL_PORT") or (465 if _ssl else 587)),
        "username": os.environ.get("EMAIL_HOST_USER", ""),
        "password": os.environ.get("EMAIL_HOST_PASSWORD", ""),
        "use_ssl": _ssl,
        "use_tls": not _ssl and os.environ.get("EMAIL_USE_TLS", "1") == "1",
    }
else:
    _smtp = None

if _smtp:
    _smtp["timeout"] = 30  # seconds; a hung server must not stall the send_outbox cron run forever
    MAILERS = {"default": {"BACKEND": "django.core.mail.backends.smtp.EmailBackend", "OPTIONS": _smtp}}
elif DEBUG:
    MAILERS = {"default": {"BACKEND": "django.core.mail.backends.console.EmailBackend"}}
else:
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.filebased.EmailBackend",
            "OPTIONS": {"file_path": str(BASE_DIR.parent / "logs" / "emails")},
        }
    }

# The arrival promise (stores/arrival.py). Buyers are told a date range counted in business
# days from the store's close date: production, then transit, then how wide the range is.
# Any store can override any of the three; blank on the store means the default here.
DEFAULT_PRODUCTION_LEAD_DAYS = 10
DEFAULT_SHIP_DAYS_ESTIMATE = 3
DEFAULT_ARRIVAL_BUFFER_DAYS = 4

# Days production stops, on top of the eleven US federal holidays. ISO dates, e.g.
# "2026-11-27" for the Friday after Thanksgiving.
BUSINESS_HOLIDAYS = []

# What a local school is billed for one group-delivery drop-off — the whole order, a few
# boxes, not per buyer. Billed to the organization, so it never reaches Stripe or a buyer.
DEFAULT_GROUP_DELIVERY_FEE = 30

# What buyers pay extra for the bigger sizes, unless a store product overrides it. This is
# retail pricing and ours alone: the ops catalog carries what a blank costs us, not this.
DEFAULT_SIZE_UPCHARGES = {"2XL": "2.00", "3XL": "3.00", "4XL": "4.00", "5XL": "5.00"}

# The ops system's catalog API, on its own EC2 instance and its own database — never shared
# (see "Not yet built" in CLAUDE.md). The token is a service credential issued over there by
# `manage.py channel_api_token create`, scoped to catalog:read.
# Both blank means no ops link, which is the normal state until the catalog sync is built;
# catalog/checks.py complains only when one is set without the other.
OPS_API_URL = os.environ.get("OPS_API_URL", "").rstrip("/")
OPS_API_TOKEN = os.environ.get("OPS_API_TOKEN", "")

STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")

LOGIN_URL = "/console/login/"
LOGIN_REDIRECT_URL = "/console/"
