# Generated by Django 6.1.1 on 2026-09-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursor', models.CharField(blank=True, help_text='The server_time from the last fully successful sync. Blank = next run is a full sync.', max_length=40)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_full_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, help_text='Why the last run stopped, or blank if it finished.')),
                ('styles_seen', models.PositiveIntegerField(default=0, help_text='Styles in the last successful run.')),
            ],
            options={
                'verbose_name': 'catalog sync state',
            },
        ),
    ]
