# Generated by Django 6.1.1 on 2026-09-22 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='False once ops archives it. Rows are never deleted.')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='When a sync first saw this go inactive. Drives the staff exceptions list.', null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('style_id', models.PositiveIntegerField(help_text='Ops style ID. Our key for a blank.', unique=True)),
                ('supplier_style_code', models.CharField(db_index=True, help_text="Ops style_name, e.g. CC1567 — the canonical code, not a supplier's internal ID.", max_length=64)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('display_title', models.CharField(blank=True, help_text="Supplier catalog copy. STAFF-FACING ONLY — never show it to buyers; use the store's own name for the product, or merch_label.", max_length=255)),
                ('merch_label', models.CharField(blank=True, help_text='Customer-facing garment name from ops marketing. Blank on most styles today.', max_length=200)),
                ('category', models.CharField(blank=True, help_text='Ops category name, free text.', max_length=120)),
                ('audience', models.CharField(blank=True, choices=[('adult', 'Adult'), ('youth', 'Youth'), ('toddler', 'Toddler')], max_length=20)),
                ('stock_policy', models.CharField(blank=True, choices=[('stocked', 'Stocked'), ('seasonal', 'Seasonal'), ('sell_down', 'Selling down'), ('job_only', 'Ordered per job')], max_length=20)),
                ('base_cost', models.DecimalField(blank=True, decimal_places=2, help_text='What ops pays today for the cheapest active variant. Internal only, never shown to buyers.', max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('size_chart', models.JSONField(blank=True, help_text='Always null in API v1.', null=True)),
                ('ops_updated_at', models.DateTimeField(help_text="The style's updated_at on ops, as sent.")),
            ],
            options={
                'ordering': ['brand', 'supplier_style_code'],
            },
        ),
        migrations.CreateModel(
            name='BlankImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(help_text="Matches a variant's color_name.", max_length=80)),
                ('image_type', models.CharField(blank=True, help_text="Supplier's own label: large, swatch, …", max_length=40)),
                ('view', models.CharField(blank=True, help_text='Always blank in API v1; reserved for front/back.', max_length=20)),
                ('url', models.URLField(help_text='Supplier CDN, hotlinked. It can change or vanish — cache anything we rely on.', max_length=500)),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.blank')),
            ],
            options={
                'ordering': ['color_name', 'image_type'],
            },
        ),
        migrations.CreateModel(
            name='BlankVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='False once ops archives it. Rows are never deleted.')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='When a sync first saw this go inactive. Drives the staff exceptions list.', null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('blank_sku', models.CharField(help_text='Ops-minted. Our key for a variant.', max_length=100, unique=True)),
                ('color_name', models.CharField(help_text='Ops colour token, e.g. BlueJean.', max_length=80)),
                ('color_hex', models.CharField(blank=True, max_length=7)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('size_sort_order', models.IntegerField(blank=True, help_text='Sort ascending for display. Not contiguous.', null=True)),
                ('cost_adjustment', models.DecimalField(blank=True, decimal_places=2, help_text="This variant's cost minus the style's base cost. Our cost, not a buyer upcharge.", max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('stock_policy', models.CharField(blank=True, choices=[('stocked', 'Stocked'), ('seasonal', 'Seasonal'), ('sell_down', 'Selling down'), ('job_only', 'Ordered per job')], max_length=20)),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.blank')),
            ],
            options={
                'ordering': ['blank', 'color_name', 'size_sort_order', 'size'],
            },
        ),
    ]
