# Generated by Django 6.1.1 on 2026-09-22 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_blank_blankimage_blankvariant'),
        ('stores', '0010_store_share_kit_error'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storeproduct',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='blank',
            field=models.ForeignKey(blank=True, help_text='The ops style this is sold from.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_offerings', to='catalog.blank'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='description',
            field=models.TextField(blank=True, help_text='Shown to buyers. The ops catalog has no buyer-facing copy.'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='image',
            field=models.ImageField(blank=True, help_text="Shown to buyers. Ops' supplier images are missing for most styles.", upload_to='store_products/'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='size_upcharges',
            field=models.JSONField(blank=True, default=dict, help_text='What buyers pay extra for a size, e.g. {"2XL": "2.00"}. Empty = the site default. Nothing to do with what the blank costs us.'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='product',
            field=models.ForeignKey(blank=True, help_text="Legacy hand-made catalog. Being replaced by blank; don't use for new products.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_offerings', to='catalog.product'),
        ),
        migrations.AddConstraint(
            model_name='storeproduct',
            constraint=models.UniqueConstraint(fields=('store', 'blank'), name='one_offering_per_blank_per_store'),
        ),
        migrations.AddConstraint(
            model_name='storeproduct',
            constraint=models.UniqueConstraint(fields=('store', 'product'), name='one_offering_per_product_per_store'),
        ),
        migrations.AddConstraint(
            model_name='storeproduct',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('blank__isnull', False), ('product__isnull', True)), models.Q(('blank__isnull', True), ('product__isnull', False)), _connector='OR'), name='offering_has_exactly_one_source'),
        ),
    ]
