# Generated by Django 6.1.1 on 2026-09-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_storeproduct_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='offered_variants',
            field=models.ManyToManyField(blank=True, help_text='The colours and sizes this store sells. Empty means every active variant, which is almost never what a school store wants.', related_name='offered_in', to='catalog.blankvariant'),
        ),
    ]
