# Generated by Django 6.1.1 on 2026-09-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='primary_color',
            field=models.CharField(default='#111827', help_text='Hex color for the store header and buttons, e.g. #1e3a8a.', max_length=7),
        ),
    ]
