# Generated by Django 6.1.1 on 2026-09-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_client_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='primary_color',
            field=models.CharField(blank=True, help_text="Hex color for this store, e.g. #228B22. Blank = use the client's color.", max_length=7),
        ),
    ]
