# Generated by Django 6.1.1 on 2026-09-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, help_text='Shown in the store header.', upload_to='clients/logos/'),
        ),
    ]
