# Generated by Django 6.1.1 on 2026-09-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_storestatuschange'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='arrival_buffer_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many business days wide the arrival range is. Blank = the site default.', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='production_lead_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Business days to produce this store's order once it closes. Blank = the site default.", null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='ship_days_estimate',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Business days in transit after production. Blank = the site default.', null=True),
        ),
    ]
