# Generated by Django 6.1.1 on 2026-09-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_store_arrival_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Street address the whole group order goes to. Shown to buyers.'),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_location_name',
            field=models.CharField(blank=True, help_text="Where a group order is handed over, e.g. 'Langley High front office'.", max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='fulfillment_mode',
            field=models.CharField(choices=[('individual_ship', 'Ship to each buyer'), ('group_ship', 'Ship one consignment to the organization'), ('group_delivery', 'Deliver to the organization ourselves')], default='individual_ship', help_text="How this store's orders reach their buyers.", max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='group_delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What the organization is billed for the whole drop-off. Never charged to buyers, never sent to Stripe. Blank = the site default.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='group_ship_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Flat delivery charge added to each buyer's order in a group-ship store. Quote it from ShipStation when setting the store up. Blank = charge nothing.", max_digits=8, null=True),
        ),
    ]
