# Generated by Django 6.1.1 on 2026-09-22 20:55

import stores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_store_fulfillment'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='share_flyer_pdf',
            field=models.FileField(blank=True, upload_to=stores.models.share_asset_path),
        ),
        migrations.AddField(
            model_name='store',
            name='share_kit_fingerprint',
            field=models.CharField(blank=True, help_text="Hash of what's printed on the share kit. Unchanged = nothing to rebuild.", max_length=64),
        ),
        migrations.AddField(
            model_name='store',
            name='share_kit_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='share_qr_png',
            field=models.FileField(blank=True, upload_to=stores.models.share_asset_path),
        ),
        migrations.AddField(
            model_name='store',
            name='share_qr_svg',
            field=models.FileField(blank=True, upload_to=stores.models.share_asset_path),
        ),
        migrations.AddField(
            model_name='store',
            name='share_social_png',
            field=models.FileField(blank=True, upload_to=stores.models.share_asset_path),
        ),
    ]
