# Generated by Django 6.1.1 on 2026-09-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_store_share_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='share_kit_error',
            field=models.TextField(blank=True, help_text='Why the last share-kit build failed. Cleared by the next build that works.'),
        ),
    ]
