# Generated by Django 6.1.1 on 2026-09-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderstatuschange'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promised_arrival_earliest',
            field=models.DateField(blank=True, help_text='Start of the arrival range shown to the buyer at checkout.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='promised_arrival_latest',
            field=models.DateField(blank=True, help_text='End of the arrival range shown to the buyer at checkout.', null=True),
        ),
    ]
