# Generated by Django 6.1.1 on 2026-09-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_promised_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Delivery charged to this buyer, snapshotted at checkout. Group ship only; a group-delivery drop-off is billed to the organization instead.', max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='recipient_label',
            field=models.CharField(blank=True, help_text="Who this line is for, e.g. 'Ava – 5th grade'. Collected per line in group stores, where one buyer often orders for several children.", max_length=120),
        ),
    ]
