# Generated by Django 6.1.1 on 2026-09-22 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_storeproduct_blank'),
        ('orders', '0005_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='blank_variant',
            field=models.ForeignKey(blank=True, help_text='The ops variant bought. Set for everything sold from a synced blank.', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.blankvariant'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Legacy catalog variant, on orders placed before the ops sync.', null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant'),
        ),
    ]
